import React from 'react';

const About = () => {
    return (
        <div className='container container--about'>
            <h2 className='header'>О нас</h2>
            <div className ='about-text'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab..</div>
            <div className ='about-text'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab.</div>
            <div className ='about-text'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab.</div>
            <div className ='about-text'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab..</div>
            <div className ='about-text'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab..</div>
            <div className ='about-text'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat ipsum voluptatum maiores nulla adipisci rem distinctio quia magni sint, accusamus dicta quisquam, velit delectus doloremque natus deserunt expedita aliquam. Ab.</div>
        </div>
    )
}

export default About;